=== mksgroup/pixelmed/source/pixelmed/src/main/java/com/pixelmed/validate/contextgroups.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">
  <xs:element name="definecontextgroups">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="definecontextgroup"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="definecontextgroup">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="contextgroupcode"/>
      </xs:sequence>
      <xs:attribute name="cid" use="required" type="xs:string"/>
      <xs:attribute name="extensible" use="required" type="xs:boolean"/>
      <xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="version" use="required" type="xs:positiveInteger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="contextgroupcode">
    <xs:complexType>
      <xs:attribute name="cm" use="required" type="xs:string"/>
      <xs:attribute name="csd" use="required" type="xs:string"/>
      <xs:attribute name="cv" use="required" type="xs:string"/>
      <xs:attribute name="csv" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mksgroup/pixelmed/source/pixelmed/src/main/java/com/pixelmed/validate/PixelMedContextGroupsSource.xml
<!-- Not used in validator at present; just place to keep track of private PMP code assignments (mostly obsolete) -->

<!-- 99PMP has the Coding Scheme UID "1.3.6.1.4.1.5962.98.1" - see com.pixelmed.dicom.VersionAndConstants-->

<definecontextgroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.pixelmed.com/schemas/contextgroups.xsd">

	<definecontextgroup cid="PMP_1" name="PixelMedPublishingSRBookFirstEditionCodes" extensible="true" version="20001022">
		<contextgroupcode csd="99PMP" cv="209001" cm="Finding"/>
		<contextgroupcode csd="99PMP" cv="209002" cm="Findings"/>
		<contextgroupcode csd="99PMP" cv="209003" cm="Initial findings"/>
		<contextgroupcode csd="99PMP" cv="209004" cm="Subsequent findings"/>
		<contextgroupcode csd="99PMP" cv="209005" cm="Conclusion"/>
		<contextgroupcode csd="99PMP" cv="209006" cm="Conclusions"/>
		<contextgroupcode csd="99PMP" cv="209007" cm="Procedure"/>
		<contextgroupcode csd="99PMP" cv="209008" cm="Procedures"/>
		<contextgroupcode csd="99PMP" cv="209009" cm="Description of procedure"/>
		<contextgroupcode csd="99PMP" cv="209010" cm="Reason for exam"/>
		<contextgroupcode csd="99PMP" cv="209011" cm="Description"/>
		<contextgroupcode csd="99PMP" cv="209013" cm="Impressions"/>
		<contextgroupcode csd="99PMP" cv="209014" cm="Impression"/>
		<contextgroupcode csd="99PMP" cv="209015" cm="Recommendations"/>
		<contextgroupcode csd="99PMP" cv="209016" cm="Recommendation"/>
		<contextgroupcode csd="99PMP" cv="209017" cm="Diagnosis"/>
		<contextgroupcode csd="99PMP" cv="209018" cm="Diagnoses"/>
		<contextgroupcode csd="99PMP" cv="209019" cm="Diagnosis codes"/>
		<contextgroupcode csd="99PMP" cv="209020" cm="Reported procedure"/>
		<contextgroupcode csd="99PMP" cv="209021" cm="Prior report"/>
		<contextgroupcode csd="99PMP" cv="209022" cm="Exam"/>
		<contextgroupcode csd="99PMP" cv="209023" cm="Image (of an exam)"/>
		<contextgroupcode csd="99PMP" cv="209024" cm="Indication"/>
		<contextgroupcode csd="99PMP" cv="209025" cm="Previous findings"/>
		<contextgroupcode csd="99PMP" cv="209026" cm="Differential diagnosis"/>
		<contextgroupcode csd="99PMP" cv="209027" cm="Procedure type"/>
		<contextgroupcode csd="99PMP" cv="209028" cm="Procedure date"/>
		<contextgroupcode csd="99PMP" cv="209029" cm="Performing physician"/>
		<contextgroupcode csd="99PMP" cv="209030" cm="Technologist"/>
		<contextgroupcode csd="99PMP" cv="209031" cm="Nurse"/>
		<contextgroupcode csd="99PMP" cv="209032" cm="Coordinates"/>
		<contextgroupcode csd="99PMP" cv="209044" cm="Seen on (as in finding seen on image)"/>
		<contextgroupcode csd="99PMP" cv="209045" cm="Key image description"/>
		<contextgroupcode csd="99PMP" cv="209046" cm="Images with findings"/>
		<contextgroupcode csd="99PMP" cv="209047" cm="Current (object or image)"/>
		<contextgroupcode csd="99PMP" cv="209048" cm="Images"/>
		<contextgroupcode csd="99PMP" cv="209049" cm="Baseline image"/>
		<contextgroupcode csd="99PMP" cv="209050" cm="Best illustration of findings"/>
		<contextgroupcode csd="99PMP" cv="209068" cm="Report"/>
		<contextgroupcode csd="99PMP" cv="209069" cm="Observer"/>
		<contextgroupcode csd="99PMP" cv="209073" cm="Report with images"/>
		<contextgroupcode csd="99PMP" cv="209074" cm="Diagnostic Imaging Report"/>
		<contextgroupcode csd="99PMP" cv="209075" cm="Radiology Report"/>
		<contextgroupcode csd="99PMP" cv="209076" cm="Chest X-ray Report"/>
		<contextgroupcode csd="99PMP" cv="209077" cm="Chest X-ray,2V,PA,Lat Report"/>
		<contextgroupcode csd="99PMP" cv="209078" cm="Projection Radiography Report"/>
		<contextgroupcode csd="99PMP" cv="209079" cm="MRI Report"/>
		<contextgroupcode csd="99PMP" cv="209098" cm="Trauma (for trauma, property of X-ray examination)"/>
		<contextgroupcode csd="99PMP" cv="209099" cm="Number of views"/>
		<contextgroupcode csd="99PMP" cv="209100" cm="Views"/>
		<contextgroupcode csd="99PMP" cv="209101" cm="View"/>
		<contextgroupcode csd="99PMP" cv="209102" cm="Modality"/>
		<contextgroupcode csd="99PMP" cv="209103" cm="Region"/>
		<contextgroupcode csd="99PMP" cv="209104" cm="Anatomic Site (syn. anatomy)"/>
		<contextgroupcode csd="99PMP" cv="209105" cm="Position (of subject wrt. gravity)"/>
		<contextgroupcode csd="99PMP" cv="209106" cm="Special (property of X-ray examination)"/>
		<contextgroupcode csd="99PMP" cv="209107" cm="Structure"/>
		<contextgroupcode csd="99PMP" cv="209108" cm="Method"/>
		<contextgroupcode csd="99PMP" cv="209109" cm="Technique"/>
		<contextgroupcode csd="99PMP" cv="209139" cm="Intra-cavitary"/>
		<contextgroupcode csd="99PMP" cv="209140" cm="Projection (radiography)"/>
		<contextgroupcode csd="99PMP" cv="209150" cm="PA and Lateral"/>
		<contextgroupcode csd="99PMP" cv="209209" cm="Unknown"/>
		<contextgroupcode csd="99PMP" cv="209210" cm="Clear (no findings)"/>
		<contextgroupcode csd="99PMP" cv="209211" cm="Absent features"/>
		<contextgroupcode csd="99PMP" cv="209212" cm="Existence negation flag"/>
		<contextgroupcode csd="99PMP" cv="209213" cm="Presence (of property)"/>
		<contextgroupcode csd="99PMP" cv="209214" cm="Normality (of finding)"/>
		<contextgroupcode csd="99PMP" cv="209215" cm="Abnormal"/>
		<contextgroupcode csd="99PMP" cv="209216" cm="Other features"/>
		<contextgroupcode csd="99PMP" cv="209217" cm="Other (unspecified choice or finding)"/>
		<contextgroupcode csd="99PMP" cv="209218" cm="Absent (not present)"/>
		<contextgroupcode csd="99PMP" cv="209219" cm="Present"/>
		<contextgroupcode csd="99PMP" cv="209220" cm="Multiple"/>
		<contextgroupcode csd="99PMP" cv="209221" cm="Single"/>
		<contextgroupcode csd="99PMP" cv="209222" cm="Clustered"/>
		<contextgroupcode csd="99PMP" cv="209223" cm="Distribution"/>
		<contextgroupcode csd="99PMP" cv="209224" cm="Pleomorphic"/>
		<contextgroupcode csd="99PMP" cv="209225" cm="Calcifications"/>
		<contextgroupcode csd="99PMP" cv="209226" cm="Malignant"/>
		<contextgroupcode csd="99PMP" cv="209227" cm="Mass"/>
		<contextgroupcode csd="99PMP" cv="209228" cm="Malignancy"/>
		<contextgroupcode csd="99PMP" cv="209229" cm="Malignant mass"/>
		<contextgroupcode csd="99PMP" cv="209230" cm="Diameter"/>
		<contextgroupcode csd="99PMP" cv="209231" cm="Normal"/>
		<contextgroupcode csd="99PMP" cv="209232" cm="Shape"/>
		<contextgroupcode csd="99PMP" cv="209233" cm="Round"/>
		<contextgroupcode csd="99PMP" cv="209234" cm="Size"/>
		<contextgroupcode csd="99PMP" cv="209235" cm="Location"/>
		<contextgroupcode csd="99PMP" cv="209236" cm="Central (location)"/>
		<contextgroupcode csd="99PMP" cv="209237" cm="Margin"/>
		<contextgroupcode csd="99PMP" cv="209238" cm="Irregular (shape or margin)"/>
		<contextgroupcode csd="99PMP" cv="209239" cm="Epicenter"/>
		<contextgroupcode csd="99PMP" cv="209240" cm="Selected volume"/>
		<contextgroupcode csd="99PMP" cv="209241" cm="Endpoints"/>
		<contextgroupcode csd="99PMP" cv="209242" cm="Density (radiographic density of lesion)"/>
		<contextgroupcode csd="99PMP" cv="209243" cm="Fat (density)"/>
		<contextgroupcode csd="99PMP" cv="209244" cm="Oval"/>
		<contextgroupcode csd="99PMP" cv="209245" cm="Lobular (shape)"/>
		<contextgroupcode csd="99PMP" cv="209246" cm="Multiplicity (of findings)"/>
		<contextgroupcode csd="99PMP" cv="209247" cm="Distribution"/>
		<contextgroupcode csd="99PMP" cv="209248" cm="Focal (distribution)"/>
		<contextgroupcode csd="99PMP" cv="209249" cm="Multifocal (distribution)"/>
		<contextgroupcode csd="99PMP" cv="209250" cm="Diffuse (distribution)"/>
		<contextgroupcode csd="99PMP" cv="209251" cm="Lucent (density)"/>
		<contextgroupcode csd="99PMP" cv="209252" cm="Sclerotic (density)"/>
		<contextgroupcode csd="99PMP" cv="209253" cm="Mixed (density)"/>
		<contextgroupcode csd="99PMP" cv="209254" cm="Area"/>
		<contextgroupcode csd="99PMP" cv="209255" cm="Volume"/>
		<contextgroupcode csd="99PMP" cv="209256" cm="Time (point in time for measurement)"/>
		<contextgroupcode csd="99PMP" cv="209257" cm="Upper limit (of normal range for measurement)"/>
		<contextgroupcode csd="99PMP" cv="209258" cm="Lower limit (of normal range for measurement)"/>
		<contextgroupcode csd="99PMP" cv="209299" cm="Projection X-ray (syn. projection radiograph)"/>
		<contextgroupcode csd="99PMP" cv="209300" cm="Chest X-ray,2V,PA,Lat"/>
		<contextgroupcode csd="99PMP" cv="209301" cm="Erect, single view, PA chest X-ray (syn. Erect, PA chest X-ray)"/>
		<contextgroupcode csd="99PMP" cv="209302" cm="Chest X-ray"/>
		<contextgroupcode csd="99PMP" cv="209303" cm="Abdominal X-ray"/>
		<contextgroupcode csd="99PMP" cv="209304" cm="Facial bones X-ray"/>
		<contextgroupcode csd="99PMP" cv="209305" cm="C-spine X-ray"/>
		<contextgroupcode csd="99PMP" cv="209306" cm="Erect and supine abdominal X-ray"/>
		<contextgroupcode csd="99PMP" cv="209307" cm="Routine facial fracture screen"/>
		<contextgroupcode csd="99PMP" cv="209308" cm="Trauma lateral c-spine X-ray"/>
		<contextgroupcode csd="99PMP" cv="209309" cm="Screening mammogram"/>
		<contextgroupcode csd="99PMP" cv="209399" cm="Bones (NOS)"/>
		<contextgroupcode csd="99PMP" cv="209400" cm="Bone lesion"/>
		<contextgroupcode csd="99PMP" cv="209401" cm="Epiphyseal (location)"/>
		<contextgroupcode csd="99PMP" cv="209402" cm="Metaphyseal (location)"/>
		<contextgroupcode csd="99PMP" cv="209403" cm="Diaphyseal (location)"/>
		<contextgroupcode csd="99PMP" cv="209404" cm="Periosteal reaction"/>
		<contextgroupcode csd="99PMP" cv="209405" cm="Solid"/>
		<contextgroupcode csd="99PMP" cv="209406" cm="Lamellated"/>
		<contextgroupcode csd="99PMP" cv="209407" cm="Sunburst"/>
		<contextgroupcode csd="99PMP" cv="209408" cm="Complex"/>
		<contextgroupcode csd="99PMP" cv="209409" cm="Codmans triangle"/>
		<contextgroupcode csd="99PMP" cv="209410" cm="Soft tissue mass"/>
		<contextgroupcode csd="99PMP" cv="209411" cm="Soft tissue calcification"/>
		<contextgroupcode csd="99PMP" cv="209412" cm="Dystrophic (calcification)"/>
		<contextgroupcode csd="99PMP" cv="209413" cm="Amorphous (calcification)"/>
