<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE DataDictionary [
<!ELEMENT DataDictionary (DataElement*)>
<!ELEMENT DataElement (Group,Element,VR,VMMin,VMMax,Keyword,Name)>
<!ELEMENT Group (#PCDATA)>
<!ELEMENT Element (#PCDATA)>
<!ELEMENT VR (#PCDATA)>
<!ELEMENT VMMin (#PCDATA)>
<!ELEMENT VMMax (#PCDATA)>
<!ELEMENT Keyword (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
]>

<DataDictionary xmlns:Dicom="http://www.nema.org/medical/dicom">
	<DataElement><Group>0x0000</Group><Element>0x0000</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CommandGroupLength</Keyword><Name>Command Group Length</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0001</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CommandLengthToEnd</Keyword><Name>Command Length to End</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0002</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>AffectedSOPClassUID</Keyword><Name>Affected SOP Class UID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0003</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RequestedSOPClassUID</Keyword><Name>Requested SOP Class UID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0010</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CommandRecognitionCode</Keyword><Name>Command Recognition Code</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0100</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CommandField</Keyword><Name>Command Field</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0110</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MessageID</Keyword><Name>Message ID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0120</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MessageIDBeingRespondedTo</Keyword><Name>Message ID Being Responded To</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0200</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Initiator</Keyword><Name>Initiator</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0300</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Receiver</Keyword><Name>Receiver</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0400</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>FindLocation</Keyword><Name>Find Location</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0600</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MoveDestination</Keyword><Name>Move Destination</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0700</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Priority</Keyword><Name>Priority</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0800</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CommandDataSetType</Keyword><Name>Command Data Set Type</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0850</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>NumberOfMatches</Keyword><Name>Number of Matches</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0860</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ResponseSequenceNumber</Keyword><Name>Response Sequence Number</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0900</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Status</Keyword><Name>Status</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0901</Element><VR>AT</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>OffendingElement</Keyword><Name>Offending Element</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0902</Element><VR>LO</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ErrorComment</Keyword><Name>Error Comment</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x0903</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ErrorID</Keyword><Name>Error ID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1000</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>AffectedSOPInstanceUID</Keyword><Name>Affected SOP Instance UID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1001</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RequestedSOPInstanceUID</Keyword><Name>Requested SOP Instance UID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1002</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>EventTypeID</Keyword><Name>Event Type ID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1005</Element><VR>AT</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>AttributeIdentifierList</Keyword><Name>Attribute Identifier List</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1008</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ActionTypeID</Keyword><Name>Action Type ID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1020</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>NumberOfRemainingSuboperations</Keyword><Name>Number of Remaining Sub-operations</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1021</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>NumberOfCompletedSuboperations</Keyword><Name>Number of Completed Sub-operations</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1022</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>NumberOfFailedSuboperations</Keyword><Name>Number of Failed Sub-operations</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1023</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>NumberOfWarningSuboperations</Keyword><Name>Number of Warning Sub-operations</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1030</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MoveOriginatorApplicationEntityTitle</Keyword><Name>Move Originator Application Entity Title</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x1031</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MoveOriginatorMessageID</Keyword><Name>Move Originator Message ID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x4000</Element><VR>LT</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>DialogReceiver</Keyword><Name>Dialog Receiver</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x4010</Element><VR>LT</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>TerminalType</Keyword><Name>Terminal Type</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5010</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MessageSetID</Keyword><Name>Message Set ID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5020</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>EndMessageID</Keyword><Name>End Message ID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5110</Element><VR>LT</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>DisplayFormat</Keyword><Name>Display Format</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5120</Element><VR>LT</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>PagePositionID</Keyword><Name>Page Position ID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5130</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>TextFormatID</Keyword><Name>Text Format ID</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5140</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>NormalReverse</Keyword><Name>Normal/Reverse</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5150</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>AddGrayScale</Keyword><Name>Add Gray Scale</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5160</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Borders</Keyword><Name>Borders</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5170</Element><VR>IS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Copies</Keyword><Name>Copies</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5180</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CommandMagnificationType</Keyword><Name>Command Magnification Type</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x5190</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Erase</Keyword><Name>Erase</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x51A0</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Print</Keyword><Name>Print</Name></DataElement>
	<DataElement><Group>0x0000</Group><Element>0x51B0</Element><VR>US</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>Overlays</Keyword><Name>Overlays</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0000</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>FileMetaInformationGroupLength</Keyword><Name>File Meta Information Group Length</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0001</Element><VR>OB</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>FileMetaInformationVersion</Keyword><Name>File Meta Information Version</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0002</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MediaStorageSOPClassUID</Keyword><Name>Media Storage SOP Class UID</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0003</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MediaStorageSOPInstanceUID</Keyword><Name>Media Storage SOP Instance UID</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0010</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>TransferSyntaxUID</Keyword><Name>Transfer Syntax UID</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0012</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ImplementationClassUID</Keyword><Name>Implementation Class UID</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0013</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ImplementationVersionName</Keyword><Name>Implementation Version Name</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0016</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>SourceApplicationEntityTitle</Keyword><Name>Source Application Entity Title</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0017</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>SendingApplicationEntityTitle</Keyword><Name>Sending Application Entity Title</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0018</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ReceivingApplicationEntityTitle</Keyword><Name>Receiving Application Entity Title</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0026</Element><VR>UR</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>SourcePresentationAddress</Keyword><Name>Source Presentation Address</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0027</Element><VR>UR</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>SendingPresentationAddress</Keyword><Name>Sending Presentation Address</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0028</Element><VR>UR</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ReceivingPresentationAddress</Keyword><Name>Receiving Presentation Address</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0031</Element><VR>OB</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RTVMetaInformationVersion</Keyword><Name>RTV Meta Information Version</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0032</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RTVCommunicationSOPClassUID</Keyword><Name>RTV Communication SOP Class UID</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0033</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RTVCommunicationSOPInstanceUID</Keyword><Name>RTV Communication SOP Instance UID</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0035</Element><VR>OB</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RTVSourceIdentifier</Keyword><Name>RTV Source Identifier</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0036</Element><VR>OB</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RTVFlowIdentifier</Keyword><Name>RTV Flow Identifier</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0037</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RTVFlowRTPSamplingRate</Keyword><Name>RTV Flow RTP Sampling Rate</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0038</Element><VR>FD</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RTVFlowActualFrameDuration</Keyword><Name>RTV Flow Actual Frame Duration</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0100</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>PrivateInformationCreatorUID</Keyword><Name>Private Information Creator UID</Name></DataElement>
	<DataElement><Group>0x0002</Group><Element>0x0102</Element><VR>OB</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>PrivateInformation</Keyword><Name>Private Information</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1130</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>FileSetID</Keyword><Name>File-set ID</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1141</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>8</VMMax><Keyword>FileSetDescriptorFileID</Keyword><Name>File-set Descriptor File ID</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1142</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>SpecificCharacterSetOfFileSetDescriptorFile</Keyword><Name>Specific Character Set of File-set Descriptor File</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1200</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>OffsetOfTheFirstDirectoryRecordOfTheRootDirectoryEntity</Keyword><Name>Offset of the First Directory Record of the Root Directory Entity</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1202</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>OffsetOfTheLastDirectoryRecordOfTheRootDirectoryEntity</Keyword><Name>Offset of the Last Directory Record of the Root Directory Entity</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1212</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>FileSetConsistencyFlag</Keyword><Name>File-set Consistency Flag</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1220</Element><VR>SQ</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>DirectoryRecordSequence</Keyword><Name>Directory Record Sequence</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1400</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>OffsetOfTheNextDirectoryRecord</Keyword><Name>Offset of the Next Directory Record</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1410</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RecordInUseFlag</Keyword><Name>Record In-use Flag</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1420</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>OffsetOfReferencedLowerLevelDirectoryEntity</Keyword><Name>Offset of Referenced Lower-Level Directory Entity</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1430</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>DirectoryRecordType</Keyword><Name>Directory Record Type</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1432</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>PrivateRecordUID</Keyword><Name>Private Record UID</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1500</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>8</VMMax><Keyword>ReferencedFileID</Keyword><Name>Referenced File ID</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1504</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MRDRDirectoryRecordOffset</Keyword><Name>MRDR Directory Record Offset</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1510</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ReferencedSOPClassUIDInFile</Keyword><Name>Referenced SOP Class UID in File</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1511</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ReferencedSOPInstanceUIDInFile</Keyword><Name>Referenced SOP Instance UID in File</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1512</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ReferencedTransferSyntaxUIDInFile</Keyword><Name>Referenced Transfer Syntax UID in File</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x151A</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>ReferencedRelatedGeneralSOPClassUIDInFile</Keyword><Name>Referenced Related General SOP Class UID in File</Name></DataElement>
	<DataElement><Group>0x0004</Group><Element>0x1600</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>NumberOfReferences</Keyword><Name>Number of References</Name></DataElement>
	<DataElement><Group>0x0006</Group><Element>0x0001</Element><VR>SQ</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CurrentFrameFunctionalGroupsSequence</Keyword><Name>Current Frame Functional Groups Sequence</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0001</Element><VR>UL</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>LengthToEnd</Keyword><Name>Length to End</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0005</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>SpecificCharacterSet</Keyword><Name>Specific Character Set</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0006</Element><VR>SQ</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>LanguageCodeSequence</Keyword><Name>Language Code Sequence</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0008</Element><VR>CS</VR><VMMin>2</VMMin><VMMax>n</VMMax><Keyword>ImageType</Keyword><Name>Image Type</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0010</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>RecognitionCode</Keyword><Name>Recognition Code</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0012</Element><VR>DA</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>InstanceCreationDate</Keyword><Name>Instance Creation Date</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0013</Element><VR>TM</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>InstanceCreationTime</Keyword><Name>Instance Creation Time</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0014</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>InstanceCreatorUID</Keyword><Name>Instance Creator UID</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0015</Element><VR>DT</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>InstanceCoercionDateTime</Keyword><Name>Instance Coercion DateTime</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0016</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>SOPClassUID</Keyword><Name>SOP Class UID</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0018</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>SOPInstanceUID</Keyword><Name>SOP Instance UID</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x001A</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>RelatedGeneralSOPClassUID</Keyword><Name>Related General SOP Class UID</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x001B</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>OriginalSpecializedSOPClassUID</Keyword><Name>Original Specialized SOP Class UID</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0020</Element><VR>DA</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>StudyDate</Keyword><Name>Study Date</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0021</Element><VR>DA</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>SeriesDate</Keyword><Name>Series Date</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0022</Element><VR>DA</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>AcquisitionDate</Keyword><Name>Acquisition Date</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0023</Element><VR>DA</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ContentDate</Keyword><Name>Content Date</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0024</Element><VR>DA</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>OverlayDate</Keyword><Name>Overlay Date</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0025</Element><VR>DA</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CurveDate</Keyword><Name>Curve Date</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x002A</Element><VR>DT</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>AcquisitionDateTime</Keyword><Name>Acquisition DateTime</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0030</Element><VR>TM</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>StudyTime</Keyword><Name>Study Time</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0031</Element><VR>TM</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>SeriesTime</Keyword><Name>Series Time</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0032</Element><VR>TM</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>AcquisitionTime</Keyword><Name>Acquisition Time</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0033</Element><VR>TM</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ContentTime</Keyword><Name>Content Time</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0034</Element><VR>TM</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>OverlayTime</Keyword><Name>Overlay Time</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0035</Element><VR>TM</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CurveTime</Keyword><Name>Curve Time</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0040</Element><VR>US</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>DataSetType</Keyword><Name>Data Set Type</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0041</Element><VR>LO</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>DataSetSubtype</Keyword><Name>Data Set Subtype</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0042</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>NuclearMedicineSeriesType</Keyword><Name>Nuclear Medicine Series Type</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0050</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>AccessionNumber</Keyword><Name>Accession Number</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0051</Element><VR>SQ</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>IssuerOfAccessionNumberSequence</Keyword><Name>Issuer of Accession Number Sequence</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0052</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>QueryRetrieveLevel</Keyword><Name>Query/Retrieve Level</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0053</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>QueryRetrieveView</Keyword><Name>Query/Retrieve View</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0054</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>RetrieveAETitle</Keyword><Name>Retrieve AE Title</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0055</Element><VR>AE</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>StationAETitle</Keyword><Name>Station AE Title</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0056</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>InstanceAvailability</Keyword><Name>Instance Availability</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0058</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>FailedSOPInstanceUIDList</Keyword><Name>Failed SOP Instance UID List</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0060</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Modality</Keyword><Name>Modality</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0061</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>ModalitiesInStudy</Keyword><Name>Modalities in Study</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0062</Element><VR>UI</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>SOPClassesInStudy</Keyword><Name>SOP Classes in Study</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0063</Element><VR>SQ</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>AnatomicRegionsInStudyCodeSequence</Keyword><Name>Anatomic Regions in Study Code Sequence</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0064</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ConversionType</Keyword><Name>Conversion Type</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0068</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>PresentationIntentType</Keyword><Name>Presentation Intent Type</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0070</Element><VR>LO</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>Manufacturer</Keyword><Name>Manufacturer</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0080</Element><VR>LO</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>InstitutionName</Keyword><Name>Institution Name</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0081</Element><VR>ST</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>InstitutionAddress</Keyword><Name>Institution Address</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0082</Element><VR>SQ</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>InstitutionCodeSequence</Keyword><Name>Institution Code Sequence</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0090</Element><VR>PN</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ReferringPhysicianName</Keyword><Name>Referring Physician&apos;s Name</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0092</Element><VR>ST</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ReferringPhysicianAddress</Keyword><Name>Referring Physician&apos;s Address</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0094</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>ReferringPhysicianTelephoneNumbers</Keyword><Name>Referring Physician&apos;s Telephone Numbers</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0096</Element><VR>SQ</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ReferringPhysicianIdentificationSequence</Keyword><Name>Referring Physician Identification Sequence</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x009C</Element><VR>PN</VR><VMMin>1</VMMin><VMMax>n</VMMax><Keyword>ConsultingPhysicianName</Keyword><Name>Consulting Physician&apos;s Name</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x009D</Element><VR>SQ</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ConsultingPhysicianIdentificationSequence</Keyword><Name>Consulting Physician Identification Sequence</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0100</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CodeValue</Keyword><Name>Code Value</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0101</Element><VR>LO</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ExtendedCodeValue</Keyword><Name>Extended Code Value</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0102</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CodingSchemeDesignator</Keyword><Name>Coding Scheme Designator</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0103</Element><VR>SH</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CodingSchemeVersion</Keyword><Name>Coding Scheme Version</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0104</Element><VR>LO</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CodeMeaning</Keyword><Name>Code Meaning</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0105</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>MappingResource</Keyword><Name>Mapping Resource</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0106</Element><VR>DT</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ContextGroupVersion</Keyword><Name>Context Group Version</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0107</Element><VR>DT</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ContextGroupLocalVersion</Keyword><Name>Context Group Local Version</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0108</Element><VR>LT</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ExtendedCodeMeaning</Keyword><Name>Extended Code Meaning</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x0109</Element><VR>SQ</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CodingSchemeResourcesSequence</Keyword><Name>Coding Scheme Resources Sequence</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x010A</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>CodingSchemeURLType</Keyword><Name>Coding Scheme URL Type</Name></DataElement>
	<DataElement><Group>0x0008</Group><Element>0x010B</Element><VR>CS</VR><VMMin>1</VMMin><VMMax>1</VMMax><Keyword>ContextGroupExtensionFlag</Keyword><Name>Context Group Extension Flag</Name></DataElement>